version: 2
jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
      KUBECONFIG: /home/circleci/.kube/config
    working_directory: ~/repo
    # gets around pyenv with circleci: https://discuss.circleci.com/t/testing-in-different-environments/450/12
    dependencies:
      override:
        - sudo pip install tox tox-pyenv
        - pyenv local 2.7.12 3.5.2
    steps:
      - checkout

      - run:
          name: Installing test/lint dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -yq --no-install-recommends --fix-missing \
                curl \
                git \
                make \
                python \
                python-dev \
                python-pip \
                python-setuptools \
                python3 \
                python3-dev \
                python3-pip \
                python3-setuptools \
                python3-wheel \
                tar

      # - run:
      #     name: lint tests
      #     command: |
      #       make lint
      
      # - run:
      #     name: Run unit tests
      #     command: |
      #       make test

      - run:
          name: Installing docker dependencies
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      # - setup_remote_docker:
      #     docker_layer_caching: true

      - run:
          name: Setting up hyperkube
          command: |
            # docker will fail with `shim error: json: cannot unmarshal object into Go value of type []string` without this
            sudo service docker restart

            # run etcd, kubelet, proxy
            docker run --net=host -d quay.io/coreos/etcd:v3.2 \
              /usr/local/bin/etcd etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379 -p 2379:2379
            docker run --net=host -d -v /var/run/docker.sock:/var/run/docker.sock \
              gcr.io/google_containers/hyperkube-amd64:v1.8.5 \
              /hyperkube kubelet --api_servers=http://127.0.0.1:8080 --v=2 --address=0.0.0.0 \
              --enable_server --hostname_override=127.0.0.1 --kubeconfig=resources/config.yaml \
              --cluster_dns=10.0.0.10 --cluster_domain=cluster.local
            docker run -d --net=host --privileged gcr.io/google_containers/hyperkube-amd64:v1.8.5 \
              /hyperkube proxy --master=http://127.0.0.1:8080 --v=2

            # set up kubectl
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.9.4/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin
            kubectl cluster-info

      - run:
          name: Run e2e tests
          command: |
            # start local registry for use with mlt builds
            docker run -d -p 5000:5000 --restart=always --name registry registry:2
            # mlt requires git setup
            git config --global user.email "test@example.com"
            git config --global user.name "Test Docker User"
            # circleci uses pyenv which won't by default have python3 available
            # pyenv global 3.5.2
            make test-e2e
