apiVersion: v1
clusters:
- cluster:
    server: http://kubernetes:8080
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}